### ISSUE TITLE
Remove .idea

### ISSUE THREAD

**Issue by jcaiqueoliveira** [RaheemJnr/Android-Coding-Practice#2]
.idea should not be shared between developers, only if you are using custom rules like removing Compose components autocomplete

**Comment by RaheemJnr** [comment]
Remove this. Please check if i get it right

**Comment by jcaiqueoliveira** [comment]
still there, the .idea folder should not go to github, to do that add .idea folder to your gitignore file

**Comment by RaheemJnr** [comment]
completed this yesterday but made some mistake that made it appear on github again

**Comment by RaheemJnr** [comment]
completed this yesterday but made some mistake that made it appear on github again
